#!/bin/bash -e

PROJECT=flits
ORG_PATH="github.com/redbadger"
REPO_PATH="${ORG_PATH}/${PROJECT}"

if [ ! -h gopath/src/${REPO_PATH} ]; then
        mkdir -p gopath/src/${ORG_PATH}
        ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

eval $(go env)

go install ${REPO_PATH}
echo "${PROJECT} built."

${PWD}/bin/${PROJECT}
